<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1499702" started-at="2018-08-30T10:32:15Z" finished-at="2018-08-30T10:57:15Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1499702" started-at="2018-08-30T10:32:15Z" finished-at="2018-08-30T10:57:15Z">
      <class name="Tests.Sprint2USTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:Tests.Sprint2USTest@af26ee]" name="setUp" is-config="true" duration-ms="5312" started-at="2018-08-30T10:32:15Z" finished-at="2018-08-30T10:32:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyAuthorCanScheduleContent()[pri:0, instance:Tests.Sprint2USTest@af26ee]" name="verifyAuthorCanScheduleContent" duration-ms="1493617" started-at="2018-08-30T10:32:20Z" description="Verify Authors can schedule when to publish and unpublish certain content" finished-at="2018-08-30T10:57:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Text not matching with Not scheduled expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Text not matching with Not scheduled expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at Tests.Sprint2USTest.verifyAuthorCanScheduleContent(Sprint2USTest.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAuthorCanScheduleContent -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Tests.Sprint2USTest@af26ee]" name="tearDown" is-config="true" duration-ms="748" started-at="2018-08-30T10:57:14Z" finished-at="2018-08-30T10:57:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Sprint2USTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
