<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="27315" started-at="2018-07-16T12:34:52Z" finished-at="2018-07-16T12:35:20Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="27315" started-at="2018-07-16T12:34:52Z" finished-at="2018-07-16T12:35:20Z">
      <class name="Tests.Sprint1USTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:Tests.Sprint1USTest@af26ee]" name="setUp" is-config="true" duration-ms="7533" started-at="2018-07-16T12:34:52Z" finished-at="2018-07-16T12:35:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyContactUsImportFunctionality()[pri:0, instance:Tests.Sprint1USTest@af26ee]" name="verifyContactUsImportFunctionality" duration-ms="18754" started-at="2018-07-16T12:35:00Z" description="Verify coty import contact location functionality" finished-at="2018-07-16T12:35:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Success Message Not Displayed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Success Message Not Displayed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at Tests.Sprint1USTest.verifyContactUsImportFunctionality(Sprint1USTest.java:153)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyContactUsImportFunctionality -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Tests.Sprint1USTest@af26ee]" name="tearDown" is-config="true" duration-ms="964" started-at="2018-07-16T12:35:19Z" finished-at="2018-07-16T12:35:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Sprint1USTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
